# Generated by Django 2.2 on 2021-08-02 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_authors_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='desc',
            new_name='description',
        ),
    ]
